from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional
import numpy as np

@dataclass
class World:
    """
    The universal data carrier and reasoning substrate for TELOS.
    
    This is the only currency the Runtime understands. 
    It is generated by the DomainSimulator and consumed by 
    the CounterfactualEngine, SafetyGate, and RTE.
    """
    state: np.ndarray
    # Metadata that allows the runtime to reason without domain knowledge
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # Semantic pointers
    entities: List[str] = field(default_factory=list)
    affordances: List[str] = field(default_factory=list)
    
    # Uncertainty/Safety metrics
    uncertainty: float = 0.0
    safety_score: float = 1.0
    
    # Causal context
    parent_action: Optional[np.ndarray] = None
    
    def to_latent(self, adapter: Any) -> np.ndarray:
        """Projects the world state into the RTE latent space."""
        return adapter.forward(self.state)

    def is_valid(self) -> bool:
        """Runtime-level sanity check."""
        return not np.isnan(self.state).any()
